"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getAssetPath = exports.noop = void 0;
const node_path_1 = require("node:path");
const node_fs_1 = require("node:fs");
const PATH = "../../assets";
const PRIVATE_PATH = (0, node_path_1.join)(PATH, "private");
const hasPrivateAssets = (0, node_fs_1.existsSync)((0, node_path_1.join)(PRIVATE_PATH, "package.json"));
const checkAsset = (file) => hasPrivateAssets && (0, node_fs_1.existsSync)((0, node_path_1.join)(PRIVATE_PATH, file)) ? "private" : "public";
const noop = () => null;
exports.noop = noop;
const getAssetPath = (path) => (0, node_path_1.join)(PATH, checkAsset(path), path);
exports.getAssetPath = getAssetPath;
